// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adgroup.sql

package dbsqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdGroupsByAdvertiser = `-- name: CountActiveAdGroupsByAdvertiser :one
SELECT COUNT(*) FROM ad_group ag JOIN campaign c ON ag.campaign_id = c.id
WHERE c.advertiser_id = $1 AND ag.status = 1
`

func (q *Queries) CountActiveAdGroupsByAdvertiser(ctx context.Context, advertiserID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdGroupsByAdvertiser, advertiserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdGroups = `-- name: CountAdGroups :one
SELECT COUNT(*) FROM ad_group WHERE ($1::bigint IS NULL OR $1::bigint = 0 OR campaign_id = $1::bigint)
  AND ($2::smallint IS NULL OR status = $2::smallint)
`

type CountAdGroupsParams struct {
	CampaignID *int64 `json:"campaign_id"`
	Status     *int16 `json:"status"`
}

func (q *Queries) CountAdGroups(ctx context.Context, arg *CountAdGroupsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdGroups, arg.CampaignID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdGroup = `-- name: CreateAdGroup :one
INSERT INTO ad_group (campaign_id, name, bid_type, bid_price, daily_budget, freq_cap, freq_period, targeting, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, version, created_at, updated_at
`

type CreateAdGroupParams struct {
	CampaignID  int64           `json:"campaign_id"`
	Name        string          `json:"name"`
	BidType     int16           `json:"bid_type"`
	BidPrice    float64         `json:"bid_price"`
	DailyBudget pgtype.Numeric  `json:"daily_budget"`
	FreqCap     *int32          `json:"freq_cap"`
	FreqPeriod  *int32          `json:"freq_period"`
	Targeting   json.RawMessage `json:"targeting"`
	Status      *int16          `json:"status"`
}

type CreateAdGroupRow struct {
	ID        int64              `json:"id"`
	Version   *int64             `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAdGroup(ctx context.Context, arg *CreateAdGroupParams) (*CreateAdGroupRow, error) {
	row := q.db.QueryRow(ctx, createAdGroup,
		arg.CampaignID,
		arg.Name,
		arg.BidType,
		arg.BidPrice,
		arg.DailyBudget,
		arg.FreqCap,
		arg.FreqPeriod,
		arg.Targeting,
		arg.Status,
	)
	var i CreateAdGroupRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAdGroup = `-- name: GetAdGroup :one
SELECT id, campaign_id, name, bid_type, bid_price, daily_budget, freq_cap, freq_period, targeting, status, version, created_at, updated_at
FROM ad_group WHERE id = $1
`

func (q *Queries) GetAdGroup(ctx context.Context, id int64) (*AdGroup, error) {
	row := q.db.QueryRow(ctx, getAdGroup, id)
	var i AdGroup
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.BidType,
		&i.BidPrice,
		&i.DailyBudget,
		&i.FreqCap,
		&i.FreqPeriod,
		&i.Targeting,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listActiveAdGroups = `-- name: ListActiveAdGroups :many
SELECT ag.id, ag.campaign_id, ag.name, ag.bid_type, ag.bid_price, ag.daily_budget,
       ag.freq_cap, ag.freq_period, ag.targeting, ag.status, ag.version,
       c.advertiser_id AS advertiser_id, c.start_time AS campaign_start_time, c.end_time AS campaign_end_time
FROM ad_group ag
INNER JOIN campaign c ON c.id = ag.campaign_id
WHERE ag.status = $1 AND c.status = $2
`

type ListActiveAdGroupsParams struct {
	Status   *int16 `json:"status"`
	Status_2 *int16 `json:"status_2"`
}

type ListActiveAdGroupsRow struct {
	ID                int64              `json:"id"`
	CampaignID        int64              `json:"campaign_id"`
	Name              string             `json:"name"`
	BidType           int16              `json:"bid_type"`
	BidPrice          float64            `json:"bid_price"`
	DailyBudget       pgtype.Numeric     `json:"daily_budget"`
	FreqCap           *int32             `json:"freq_cap"`
	FreqPeriod        *int32             `json:"freq_period"`
	Targeting         json.RawMessage    `json:"targeting"`
	Status            *int16             `json:"status"`
	Version           *int64             `json:"version"`
	AdvertiserID      int64              `json:"advertiser_id"`
	CampaignStartTime pgtype.Timestamptz `json:"campaign_start_time"`
	CampaignEndTime   pgtype.Timestamptz `json:"campaign_end_time"`
}

func (q *Queries) ListActiveAdGroups(ctx context.Context, arg *ListActiveAdGroupsParams) ([]*ListActiveAdGroupsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAdGroups, arg.Status, arg.Status_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListActiveAdGroupsRow
	for rows.Next() {
		var i ListActiveAdGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.BidType,
			&i.BidPrice,
			&i.DailyBudget,
			&i.FreqCap,
			&i.FreqPeriod,
			&i.Targeting,
			&i.Status,
			&i.Version,
			&i.AdvertiserID,
			&i.CampaignStartTime,
			&i.CampaignEndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdGroups = `-- name: ListAdGroups :many
SELECT id, campaign_id, name, bid_type, bid_price, daily_budget, freq_cap, freq_period, targeting, status, version, created_at, updated_at
FROM ad_group WHERE ($1::bigint IS NULL OR $1::bigint = 0 OR campaign_id = $1::bigint)
  AND ($2::smallint IS NULL OR status = $2::smallint)
ORDER BY created_at DESC LIMIT $4 OFFSET $3
`

type ListAdGroupsParams struct {
	CampaignID *int64 `json:"campaign_id"`
	Status     *int16 `json:"status"`
	Offset     int32  `json:"offset"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) ListAdGroups(ctx context.Context, arg *ListAdGroupsParams) ([]*AdGroup, error) {
	rows, err := q.db.Query(ctx, listAdGroups,
		arg.CampaignID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AdGroup
	for rows.Next() {
		var i AdGroup
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.BidType,
			&i.BidPrice,
			&i.DailyBudget,
			&i.FreqCap,
			&i.FreqPeriod,
			&i.Targeting,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdGroup = `-- name: UpdateAdGroup :one
UPDATE ad_group SET name=$1, bid_price=$2, daily_budget=$3, freq_cap=$4, targeting=$5, version=version+1, updated_at=$6
WHERE id=$7 AND version=$8
RETURNING version
`

type UpdateAdGroupParams struct {
	Name        string             `json:"name"`
	BidPrice    float64            `json:"bid_price"`
	DailyBudget pgtype.Numeric     `json:"daily_budget"`
	FreqCap     *int32             `json:"freq_cap"`
	Targeting   json.RawMessage    `json:"targeting"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          int64              `json:"id"`
	Version     *int64             `json:"version"`
}

func (q *Queries) UpdateAdGroup(ctx context.Context, arg *UpdateAdGroupParams) (*int64, error) {
	row := q.db.QueryRow(ctx, updateAdGroup,
		arg.Name,
		arg.BidPrice,
		arg.DailyBudget,
		arg.FreqCap,
		arg.Targeting,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	var version *int64
	err := row.Scan(&version)
	return version, err
}

const updateAdGroupStatus = `-- name: UpdateAdGroupStatus :exec
UPDATE ad_group SET status=$1, version=version+1, updated_at=NOW() WHERE id=$2
`

type UpdateAdGroupStatusParams struct {
	Status *int16 `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateAdGroupStatus(ctx context.Context, arg *UpdateAdGroupStatusParams) error {
	_, err := q.db.Exec(ctx, updateAdGroupStatus, arg.Status, arg.ID)
	return err
}
