// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advertiser.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdvertisers = `-- name: CountAdvertisers :one
SELECT COUNT(*) FROM advertiser
WHERE ($1::smallint IS NULL OR status = $1::smallint)
  AND ($2::smallint IS NULL OR COALESCE(qualification_status, 0) = $2::smallint)
`

type CountAdvertisersParams struct {
	Status              *int16 `json:"status"`
	QualificationStatus *int16 `json:"qualification_status"`
}

func (q *Queries) CountAdvertisers(ctx context.Context, arg *CountAdvertisersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdvertisers, arg.Status, arg.QualificationStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBalanceTransactions = `-- name: CountBalanceTransactions :one
SELECT COUNT(*) FROM balance_transaction WHERE advertiser_id = $1
`

func (q *Queries) CountBalanceTransactions(ctx context.Context, advertiserID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBalanceTransactions, advertiserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingAudits = `-- name: CountPendingAudits :one
SELECT COUNT(*) FROM (
  SELECT id FROM creative WHERE audit_status = 0
  UNION ALL
  SELECT id FROM advertiser WHERE COALESCE(qualification_status, 0) = 0
) t
`

func (q *Queries) CountPendingAudits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingAudits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE ($1::varchar IS NULL OR role = $1::varchar)
`

// Admin queries
func (q *Queries) CountUsers(ctx context.Context, role *string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdPosition = `-- name: CreateAdPosition :one
INSERT INTO ad_position (media_id, name, position_type, ad_format, width, height, max_size, duration_min, duration_max, mime_types)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id
`

type CreateAdPositionParams struct {
	MediaID      int64   `json:"media_id"`
	Name         string  `json:"name"`
	PositionType int16   `json:"position_type"`
	AdFormat     int16   `json:"ad_format"`
	Width        *int32  `json:"width"`
	Height       *int32  `json:"height"`
	MaxSize      *int32  `json:"max_size"`
	DurationMin  *int32  `json:"duration_min"`
	DurationMax  *int32  `json:"duration_max"`
	MimeTypes    *string `json:"mime_types"`
}

// Ad position queries
func (q *Queries) CreateAdPosition(ctx context.Context, arg *CreateAdPositionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAdPosition,
		arg.MediaID,
		arg.Name,
		arg.PositionType,
		arg.AdFormat,
		arg.Width,
		arg.Height,
		arg.MaxSize,
		arg.DurationMin,
		arg.DurationMax,
		arg.MimeTypes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createAdvertiser = `-- name: CreateAdvertiser :one
INSERT INTO advertiser (name, industry, contact_name, contact_email, address, website, brand_names)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id
`

type CreateAdvertiserParams struct {
	Name         string  `json:"name"`
	Industry     *string `json:"industry"`
	ContactName  *string `json:"contact_name"`
	ContactEmail *string `json:"contact_email"`
	Address      *string `json:"address"`
	Website      *string `json:"website"`
	BrandNames   *string `json:"brand_names"`
}

// Advertiser queries
func (q *Queries) CreateAdvertiser(ctx context.Context, arg *CreateAdvertiserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAdvertiser,
		arg.Name,
		arg.Industry,
		arg.ContactName,
		arg.ContactEmail,
		arg.Address,
		arg.Website,
		arg.BrandNames,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createBalanceTransaction = `-- name: CreateBalanceTransaction :exec
INSERT INTO balance_transaction (advertiser_id, amount, balance_before, balance_after, tx_type, description, operator_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateBalanceTransactionParams struct {
	AdvertiserID  int64   `json:"advertiser_id"`
	Amount        float64 `json:"amount"`
	BalanceBefore float64 `json:"balance_before"`
	BalanceAfter  float64 `json:"balance_after"`
	TxType        int16   `json:"tx_type"`
	Description   *string `json:"description"`
	OperatorID    *int64  `json:"operator_id"`
}

func (q *Queries) CreateBalanceTransaction(ctx context.Context, arg *CreateBalanceTransactionParams) error {
	_, err := q.db.Exec(ctx, createBalanceTransaction,
		arg.AdvertiserID,
		arg.Amount,
		arg.BalanceBefore,
		arg.BalanceAfter,
		arg.TxType,
		arg.Description,
		arg.OperatorID,
	)
	return err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (name, code, domain) VALUES ($1, $2, $3) RETURNING id
`

type CreateMediaParams struct {
	Name   string  `json:"name"`
	Code   string  `json:"code"`
	Domain *string `json:"domain"`
}

// Media queries
func (q *Queries) CreateMedia(ctx context.Context, arg *CreateMediaParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMedia, arg.Name, arg.Code, arg.Domain)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createProofMaterial = `-- name: CreateProofMaterial :exec
INSERT INTO proof_material (advertiser_id, material_type, file_url, file_name, file_size)
VALUES ($1, $2, $3, $4, $5)
`

type CreateProofMaterialParams struct {
	AdvertiserID int64   `json:"advertiser_id"`
	MaterialType int16   `json:"material_type"`
	FileUrl      string  `json:"file_url"`
	FileName     *string `json:"file_name"`
	FileSize     *int32  `json:"file_size"`
}

// Proof material queries
func (q *Queries) CreateProofMaterial(ctx context.Context, arg *CreateProofMaterialParams) error {
	_, err := q.db.Exec(ctx, createProofMaterial,
		arg.AdvertiserID,
		arg.MaterialType,
		arg.FileUrl,
		arg.FileName,
		arg.FileSize,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, advertiser_id, role)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
	Name         *string `json:"name"`
	AdvertiserID *int64  `json:"advertiser_id"`
	Role         *string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.AdvertiserID,
		arg.Role,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAdvertiser = `-- name: DeleteAdvertiser :exec
DELETE FROM advertiser WHERE id = $1
`

func (q *Queries) DeleteAdvertiser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAdvertiser, id)
	return err
}

const getAdvertiser = `-- name: GetAdvertiser :one
SELECT id, name, industry, contact_name, contact_email, balance, status,
       COALESCE(qualification_status, 0) as qualification_status,
       qualification_reason, COALESCE(credit_limit, 0) as credit_limit,
       address, website, brand_names, created_at, updated_at
FROM advertiser WHERE id = $1
`

type GetAdvertiserRow struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	Industry            *string            `json:"industry"`
	ContactName         *string            `json:"contact_name"`
	ContactEmail        *string            `json:"contact_email"`
	Balance             pgtype.Numeric     `json:"balance"`
	Status              *int16             `json:"status"`
	QualificationStatus int16              `json:"qualification_status"`
	QualificationReason *string            `json:"qualification_reason"`
	CreditLimit         float64            `json:"credit_limit"`
	Address             *string            `json:"address"`
	Website             *string            `json:"website"`
	BrandNames          *string            `json:"brand_names"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAdvertiser(ctx context.Context, id int64) (*GetAdvertiserRow, error) {
	row := q.db.QueryRow(ctx, getAdvertiser, id)
	var i GetAdvertiserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Industry,
		&i.ContactName,
		&i.ContactEmail,
		&i.Balance,
		&i.Status,
		&i.QualificationStatus,
		&i.QualificationReason,
		&i.CreditLimit,
		&i.Address,
		&i.Website,
		&i.BrandNames,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAdvertiserBalance = `-- name: GetAdvertiserBalance :one
SELECT COALESCE(balance, 0) as balance, COALESCE(credit_limit, 0) as credit_limit FROM advertiser WHERE id = $1
`

type GetAdvertiserBalanceRow struct {
	Balance     float64 `json:"balance"`
	CreditLimit float64 `json:"credit_limit"`
}

// Balance queries
func (q *Queries) GetAdvertiserBalance(ctx context.Context, id int64) (*GetAdvertiserBalanceRow, error) {
	row := q.db.QueryRow(ctx, getAdvertiserBalance, id)
	var i GetAdvertiserBalanceRow
	err := row.Scan(&i.Balance, &i.CreditLimit)
	return &i, err
}

const listAdPositionsByMedia = `-- name: ListAdPositionsByMedia :many
SELECT id, media_id, name, position_type, ad_format, width, height, max_size, duration_min, duration_max, mime_types, status
FROM ad_position WHERE media_id = $1 ORDER BY id
`

type ListAdPositionsByMediaRow struct {
	ID           int64   `json:"id"`
	MediaID      int64   `json:"media_id"`
	Name         string  `json:"name"`
	PositionType int16   `json:"position_type"`
	AdFormat     int16   `json:"ad_format"`
	Width        *int32  `json:"width"`
	Height       *int32  `json:"height"`
	MaxSize      *int32  `json:"max_size"`
	DurationMin  *int32  `json:"duration_min"`
	DurationMax  *int32  `json:"duration_max"`
	MimeTypes    *string `json:"mime_types"`
	Status       *int16  `json:"status"`
}

func (q *Queries) ListAdPositionsByMedia(ctx context.Context, mediaID int64) ([]*ListAdPositionsByMediaRow, error) {
	rows, err := q.db.Query(ctx, listAdPositionsByMedia, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAdPositionsByMediaRow
	for rows.Next() {
		var i ListAdPositionsByMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Name,
			&i.PositionType,
			&i.AdFormat,
			&i.Width,
			&i.Height,
			&i.MaxSize,
			&i.DurationMin,
			&i.DurationMax,
			&i.MimeTypes,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdvertisers = `-- name: ListAdvertisers :many
SELECT id, name, industry, contact_name, contact_email, balance, status,
       COALESCE(qualification_status, 0) as qualification_status,
       qualification_reason, COALESCE(credit_limit, 0) as credit_limit,
       address, website, brand_names, created_at, updated_at
FROM advertiser
WHERE ($3::smallint IS NULL OR status = $3::smallint)
  AND ($4::smallint IS NULL OR COALESCE(qualification_status, 0) = $4::smallint)
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAdvertisersParams struct {
	Limit               int32  `json:"limit"`
	Offset              int32  `json:"offset"`
	Status              *int16 `json:"status"`
	QualificationStatus *int16 `json:"qualification_status"`
}

type ListAdvertisersRow struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	Industry            *string            `json:"industry"`
	ContactName         *string            `json:"contact_name"`
	ContactEmail        *string            `json:"contact_email"`
	Balance             pgtype.Numeric     `json:"balance"`
	Status              *int16             `json:"status"`
	QualificationStatus int16              `json:"qualification_status"`
	QualificationReason *string            `json:"qualification_reason"`
	CreditLimit         float64            `json:"credit_limit"`
	Address             *string            `json:"address"`
	Website             *string            `json:"website"`
	BrandNames          *string            `json:"brand_names"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAdvertisers(ctx context.Context, arg *ListAdvertisersParams) ([]*ListAdvertisersRow, error) {
	rows, err := q.db.Query(ctx, listAdvertisers,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.QualificationStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAdvertisersRow
	for rows.Next() {
		var i ListAdvertisersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Industry,
			&i.ContactName,
			&i.ContactEmail,
			&i.Balance,
			&i.Status,
			&i.QualificationStatus,
			&i.QualificationReason,
			&i.CreditLimit,
			&i.Address,
			&i.Website,
			&i.BrandNames,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMedia = `-- name: ListAllMedia :many
SELECT id, name, code, domain, status FROM media ORDER BY id
`

type ListAllMediaRow struct {
	ID     int64   `json:"id"`
	Name   string  `json:"name"`
	Code   string  `json:"code"`
	Domain *string `json:"domain"`
	Status *int16  `json:"status"`
}

func (q *Queries) ListAllMedia(ctx context.Context) ([]*ListAllMediaRow, error) {
	rows, err := q.db.Query(ctx, listAllMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAllMediaRow
	for rows.Next() {
		var i ListAllMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Domain,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalanceTransactions = `-- name: ListBalanceTransactions :many
SELECT id, advertiser_id, amount, balance_before, balance_after, tx_type, description, operator_id, created_at
FROM balance_transaction WHERE advertiser_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListBalanceTransactionsParams struct {
	AdvertiserID int64 `json:"advertiser_id"`
	Limit        int32 `json:"limit"`
	Offset       int32 `json:"offset"`
}

func (q *Queries) ListBalanceTransactions(ctx context.Context, arg *ListBalanceTransactionsParams) ([]*BalanceTransaction, error) {
	rows, err := q.db.Query(ctx, listBalanceTransactions, arg.AdvertiserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*BalanceTransaction
	for rows.Next() {
		var i BalanceTransaction
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Amount,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.TxType,
			&i.Description,
			&i.OperatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAdvertiserAudits = `-- name: ListPendingAdvertiserAudits :many
SELECT id, 2 as audit_type, name, id as advertiser_id, name as advertiser_name,
       COALESCE(qualification_status, 0) as status, qualification_reason as reason, created_at
FROM advertiser
WHERE COALESCE(qualification_status, 0) = 0
ORDER BY created_at ASC LIMIT $1 OFFSET $2
`

type ListPendingAdvertiserAuditsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPendingAdvertiserAuditsRow struct {
	ID             int64              `json:"id"`
	AuditType      int32              `json:"audit_type"`
	Name           string             `json:"name"`
	AdvertiserID   int64              `json:"advertiser_id"`
	AdvertiserName string             `json:"advertiser_name"`
	Status         int16              `json:"status"`
	Reason         *string            `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingAdvertiserAudits(ctx context.Context, arg *ListPendingAdvertiserAuditsParams) ([]*ListPendingAdvertiserAuditsRow, error) {
	rows, err := q.db.Query(ctx, listPendingAdvertiserAudits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPendingAdvertiserAuditsRow
	for rows.Next() {
		var i ListPendingAdvertiserAuditsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuditType,
			&i.Name,
			&i.AdvertiserID,
			&i.AdvertiserName,
			&i.Status,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCreativeAudits = `-- name: ListPendingCreativeAudits :many
SELECT c.id, 1 as audit_type, c.name, ca.advertiser_id,
       COALESCE(a.name, '') as advertiser_name,
       c.audit_status as status, c.audit_reason as reason, c.created_at
FROM creative c
JOIN ad_group ag ON c.ad_group_id = ag.id
JOIN campaign ca ON ag.campaign_id = ca.id
JOIN advertiser a ON ca.advertiser_id = a.id
WHERE c.audit_status = 0
ORDER BY c.created_at ASC LIMIT $1 OFFSET $2
`

type ListPendingCreativeAuditsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPendingCreativeAuditsRow struct {
	ID             int64              `json:"id"`
	AuditType      int32              `json:"audit_type"`
	Name           string             `json:"name"`
	AdvertiserID   int64              `json:"advertiser_id"`
	AdvertiserName string             `json:"advertiser_name"`
	Status         *int16             `json:"status"`
	Reason         *string            `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingCreativeAudits(ctx context.Context, arg *ListPendingCreativeAuditsParams) ([]*ListPendingCreativeAuditsRow, error) {
	rows, err := q.db.Query(ctx, listPendingCreativeAudits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPendingCreativeAuditsRow
	for rows.Next() {
		var i ListPendingCreativeAuditsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuditType,
			&i.Name,
			&i.AdvertiserID,
			&i.AdvertiserName,
			&i.Status,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProofMaterials = `-- name: ListProofMaterials :many
SELECT id, advertiser_id, material_type, file_url, file_name, file_size, audit_status, audit_reason, created_at
FROM proof_material WHERE advertiser_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProofMaterials(ctx context.Context, advertiserID int64) ([]*ProofMaterial, error) {
	rows, err := q.db.Query(ctx, listProofMaterials, advertiserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ProofMaterial
	for rows.Next() {
		var i ProofMaterial
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.MaterialType,
			&i.FileUrl,
			&i.FileName,
			&i.FileSize,
			&i.AuditStatus,
			&i.AuditReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, advertiser_id, role, created_at FROM users
WHERE ($3::varchar IS NULL OR role = $3::varchar)
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Role   *string `json:"role"`
}

type ListUsersRow struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	Name         *string            `json:"name"`
	AdvertiserID *int64             `json:"advertiser_id"`
	Role         *string            `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg *ListUsersParams) ([]*ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AdvertiserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rechargeAdvertiser = `-- name: RechargeAdvertiser :one
UPDATE advertiser SET balance = balance + $2, updated_at = NOW() WHERE id = $1
RETURNING balance
`

type RechargeAdvertiserParams struct {
	ID      int64          `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) RechargeAdvertiser(ctx context.Context, arg *RechargeAdvertiserParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, rechargeAdvertiser, arg.ID, arg.Balance)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const updateAdPosition = `-- name: UpdateAdPosition :exec
UPDATE ad_position SET
  name = COALESCE($2, name),
  width = COALESCE($3, width),
  height = COALESCE($4, height),
  max_size = COALESCE($5, max_size),
  duration_min = COALESCE($6, duration_min),
  duration_max = COALESCE($7, duration_max)
WHERE id = $1
`

type UpdateAdPositionParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Width       *int32 `json:"width"`
	Height      *int32 `json:"height"`
	MaxSize     *int32 `json:"max_size"`
	DurationMin *int32 `json:"duration_min"`
	DurationMax *int32 `json:"duration_max"`
}

func (q *Queries) UpdateAdPosition(ctx context.Context, arg *UpdateAdPositionParams) error {
	_, err := q.db.Exec(ctx, updateAdPosition,
		arg.ID,
		arg.Name,
		arg.Width,
		arg.Height,
		arg.MaxSize,
		arg.DurationMin,
		arg.DurationMax,
	)
	return err
}

const updateAdvertiser = `-- name: UpdateAdvertiser :exec
UPDATE advertiser SET
  name = COALESCE($2, name),
  industry = COALESCE($3, industry),
  contact_name = COALESCE($4, contact_name),
  contact_email = COALESCE($5, contact_email),
  address = COALESCE($6, address),
  website = COALESCE($7, website),
  brand_names = COALESCE($8, brand_names),
  updated_at = NOW()
WHERE id = $1
`

type UpdateAdvertiserParams struct {
	ID           int64   `json:"id"`
	Name         string  `json:"name"`
	Industry     *string `json:"industry"`
	ContactName  *string `json:"contact_name"`
	ContactEmail *string `json:"contact_email"`
	Address      *string `json:"address"`
	Website      *string `json:"website"`
	BrandNames   *string `json:"brand_names"`
}

func (q *Queries) UpdateAdvertiser(ctx context.Context, arg *UpdateAdvertiserParams) error {
	_, err := q.db.Exec(ctx, updateAdvertiser,
		arg.ID,
		arg.Name,
		arg.Industry,
		arg.ContactName,
		arg.ContactEmail,
		arg.Address,
		arg.Website,
		arg.BrandNames,
	)
	return err
}

const updateAdvertiserQualification = `-- name: UpdateAdvertiserQualification :exec
UPDATE advertiser SET qualification_status = $2, qualification_reason = $3, updated_at = NOW() WHERE id = $1
`

type UpdateAdvertiserQualificationParams struct {
	ID                  int64   `json:"id"`
	QualificationStatus *int16  `json:"qualification_status"`
	QualificationReason *string `json:"qualification_reason"`
}

func (q *Queries) UpdateAdvertiserQualification(ctx context.Context, arg *UpdateAdvertiserQualificationParams) error {
	_, err := q.db.Exec(ctx, updateAdvertiserQualification, arg.ID, arg.QualificationStatus, arg.QualificationReason)
	return err
}

const updateMedia = `-- name: UpdateMedia :exec
UPDATE media SET name = COALESCE($2, name), domain = COALESCE($3, domain) WHERE id = $1
`

type UpdateMediaParams struct {
	ID     int64   `json:"id"`
	Name   string  `json:"name"`
	Domain *string `json:"domain"`
}

func (q *Queries) UpdateMedia(ctx context.Context, arg *UpdateMediaParams) error {
	_, err := q.db.Exec(ctx, updateMedia, arg.ID, arg.Name, arg.Domain)
	return err
}

const updateMediaStatus = `-- name: UpdateMediaStatus :exec
UPDATE media SET status = $2 WHERE id = $1
`

type UpdateMediaStatusParams struct {
	ID     int64  `json:"id"`
	Status *int16 `json:"status"`
}

func (q *Queries) UpdateMediaStatus(ctx context.Context, arg *UpdateMediaStatusParams) error {
	_, err := q.db.Exec(ctx, updateMediaStatus, arg.ID, arg.Status)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $2 WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   int64   `json:"id"`
	Role *string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg *UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
