// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attribution.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConversionsByAdvertiser = `-- name: CountConversionsByAdvertiser :one
SELECT COUNT(*) FROM conversion_event
WHERE advertiser_id = $1 AND event_time >= $2 AND event_time < $3
`

type CountConversionsByAdvertiserParams struct {
	AdvertiserID *int64    `json:"advertiser_id"`
	EventTime    time.Time `json:"event_time"`
	EventTime_2  time.Time `json:"event_time_2"`
}

func (q *Queries) CountConversionsByAdvertiser(ctx context.Context, arg *CountConversionsByAdvertiserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConversionsByAdvertiser, arg.AdvertiserID, arg.EventTime, arg.EventTime_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findClickID = `-- name: FindClickID :one
SELECT click_id, event_type, adgroup_id, creative_id, campaign_id, advertiser_id,
       media_id, ad_position_id, price, device_id, ip, ua, geo_city, event_time
FROM stat_event
WHERE click_id = $1 AND event_type = 2
LIMIT 1
`

type FindClickIDRow struct {
	ClickID      *string        `json:"click_id"`
	EventType    int16          `json:"event_type"`
	AdgroupID    int64          `json:"adgroup_id"`
	CreativeID   int64          `json:"creative_id"`
	CampaignID   int64          `json:"campaign_id"`
	AdvertiserID int64          `json:"advertiser_id"`
	MediaID      int64          `json:"media_id"`
	AdPositionID int64          `json:"ad_position_id"`
	Price        pgtype.Numeric `json:"price"`
	DeviceID     *string        `json:"device_id"`
	Ip           *string        `json:"ip"`
	Ua           *string        `json:"ua"`
	GeoCity      *string        `json:"geo_city"`
	EventTime    time.Time      `json:"event_time"`
}

func (q *Queries) FindClickID(ctx context.Context, clickID *string) (*FindClickIDRow, error) {
	row := q.db.QueryRow(ctx, findClickID, clickID)
	var i FindClickIDRow
	err := row.Scan(
		&i.ClickID,
		&i.EventType,
		&i.AdgroupID,
		&i.CreativeID,
		&i.CampaignID,
		&i.AdvertiserID,
		&i.MediaID,
		&i.AdPositionID,
		&i.Price,
		&i.DeviceID,
		&i.Ip,
		&i.Ua,
		&i.GeoCity,
		&i.EventTime,
	)
	return &i, err
}

const findClickIDInWindow = `-- name: FindClickIDInWindow :one
SELECT click_id, event_type, adgroup_id, creative_id, campaign_id, advertiser_id,
       media_id, ad_position_id, price, device_id, ip, ua, geo_city, event_time
FROM stat_event
WHERE click_id = $1 AND event_type = 2 AND event_time >= $2
LIMIT 1
`

type FindClickIDInWindowParams struct {
	ClickID   *string   `json:"click_id"`
	EventTime time.Time `json:"event_time"`
}

type FindClickIDInWindowRow struct {
	ClickID      *string        `json:"click_id"`
	EventType    int16          `json:"event_type"`
	AdgroupID    int64          `json:"adgroup_id"`
	CreativeID   int64          `json:"creative_id"`
	CampaignID   int64          `json:"campaign_id"`
	AdvertiserID int64          `json:"advertiser_id"`
	MediaID      int64          `json:"media_id"`
	AdPositionID int64          `json:"ad_position_id"`
	Price        pgtype.Numeric `json:"price"`
	DeviceID     *string        `json:"device_id"`
	Ip           *string        `json:"ip"`
	Ua           *string        `json:"ua"`
	GeoCity      *string        `json:"geo_city"`
	EventTime    time.Time      `json:"event_time"`
}

func (q *Queries) FindClickIDInWindow(ctx context.Context, arg *FindClickIDInWindowParams) (*FindClickIDInWindowRow, error) {
	row := q.db.QueryRow(ctx, findClickIDInWindow, arg.ClickID, arg.EventTime)
	var i FindClickIDInWindowRow
	err := row.Scan(
		&i.ClickID,
		&i.EventType,
		&i.AdgroupID,
		&i.CreativeID,
		&i.CampaignID,
		&i.AdvertiserID,
		&i.MediaID,
		&i.AdPositionID,
		&i.Price,
		&i.DeviceID,
		&i.Ip,
		&i.Ua,
		&i.GeoCity,
		&i.EventTime,
	)
	return &i, err
}

const insertConversionEvent = `-- name: InsertConversionEvent :exec
INSERT INTO conversion_event
(click_id, event_type, adgroup_id, creative_id, campaign_id, advertiser_id,
 media_id, ad_position_id, price, revenue, device_id, ip, ua, geo_city, extra, event_time)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
`

type InsertConversionEventParams struct {
	ClickID      string         `json:"click_id"`
	EventType    string         `json:"event_type"`
	AdgroupID    *int64         `json:"adgroup_id"`
	CreativeID   *int64         `json:"creative_id"`
	CampaignID   *int64         `json:"campaign_id"`
	AdvertiserID *int64         `json:"advertiser_id"`
	MediaID      *int64         `json:"media_id"`
	AdPositionID *int64         `json:"ad_position_id"`
	Price        pgtype.Numeric `json:"price"`
	Revenue      pgtype.Numeric `json:"revenue"`
	DeviceID     *string        `json:"device_id"`
	Ip           *string        `json:"ip"`
	Ua           *string        `json:"ua"`
	GeoCity      *string        `json:"geo_city"`
	Extra        []byte         `json:"extra"`
	EventTime    time.Time      `json:"event_time"`
}

func (q *Queries) InsertConversionEvent(ctx context.Context, arg *InsertConversionEventParams) error {
	_, err := q.db.Exec(ctx, insertConversionEvent,
		arg.ClickID,
		arg.EventType,
		arg.AdgroupID,
		arg.CreativeID,
		arg.CampaignID,
		arg.AdvertiserID,
		arg.MediaID,
		arg.AdPositionID,
		arg.Price,
		arg.Revenue,
		arg.DeviceID,
		arg.Ip,
		arg.Ua,
		arg.GeoCity,
		arg.Extra,
		arg.EventTime,
	)
	return err
}

const sumRevenueByAdvertiser = `-- name: SumRevenueByAdvertiser :one
SELECT COALESCE(SUM(revenue), 0)::float8 FROM conversion_event
WHERE advertiser_id = $1 AND event_time >= $2 AND event_time < $3
`

type SumRevenueByAdvertiserParams struct {
	AdvertiserID *int64    `json:"advertiser_id"`
	EventTime    time.Time `json:"event_time"`
	EventTime_2  time.Time `json:"event_time_2"`
}

func (q *Queries) SumRevenueByAdvertiser(ctx context.Context, arg *SumRevenueByAdvertiserParams) (float64, error) {
	row := q.db.QueryRow(ctx, sumRevenueByAdvertiser, arg.AdvertiserID, arg.EventTime, arg.EventTime_2)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertReportConversions = `-- name: UpsertReportConversions :exec
INSERT INTO report_hourly (hour, advertiser_id, campaign_id, ad_group_id, creative_id, media_id, ad_position_id, conversions, revenue)
VALUES (date_trunc('hour', NOW()), $1, $2, $3, $4, $5, $6, 1, $7)
ON CONFLICT (hour, ad_group_id, creative_id, media_id, ad_position_id)
DO UPDATE SET
  conversions = report_hourly.conversions + 1,
  revenue = report_hourly.revenue + EXCLUDED.revenue
`

type UpsertReportConversionsParams struct {
	AdvertiserID int64          `json:"advertiser_id"`
	CampaignID   int64          `json:"campaign_id"`
	AdGroupID    int64          `json:"ad_group_id"`
	CreativeID   int64          `json:"creative_id"`
	MediaID      int64          `json:"media_id"`
	AdPositionID int64          `json:"ad_position_id"`
	Revenue      pgtype.Numeric `json:"revenue"`
}

func (q *Queries) UpsertReportConversions(ctx context.Context, arg *UpsertReportConversionsParams) error {
	_, err := q.db.Exec(ctx, upsertReportConversions,
		arg.AdvertiserID,
		arg.CampaignID,
		arg.AdGroupID,
		arg.CreativeID,
		arg.MediaID,
		arg.AdPositionID,
		arg.Revenue,
	)
	return err
}
