// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCampaigns = `-- name: CountCampaigns :one
SELECT COUNT(*) FROM campaign WHERE advertiser_id = $1
  AND ($2::smallint IS NULL OR status = $2::smallint)
`

type CountCampaignsParams struct {
	AdvertiserID int64  `json:"advertiser_id"`
	Status       *int16 `json:"status"`
}

func (q *Queries) CountCampaigns(ctx context.Context, arg *CountCampaignsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaigns, arg.AdvertiserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaign (advertiser_id, name, budget, daily_budget, start_time, end_time, pacing, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, version, created_at, updated_at
`

type CreateCampaignParams struct {
	AdvertiserID int64              `json:"advertiser_id"`
	Name         string             `json:"name"`
	Budget       pgtype.Numeric     `json:"budget"`
	DailyBudget  pgtype.Numeric     `json:"daily_budget"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
	Pacing       *int16             `json:"pacing"`
	Status       *int16             `json:"status"`
}

type CreateCampaignRow struct {
	ID        int64              `json:"id"`
	Version   *int64             `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg *CreateCampaignParams) (*CreateCampaignRow, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.AdvertiserID,
		arg.Name,
		arg.Budget,
		arg.DailyBudget,
		arg.StartTime,
		arg.EndTime,
		arg.Pacing,
		arg.Status,
	)
	var i CreateCampaignRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, advertiser_id, name, budget, daily_budget, start_time, end_time, pacing, status, version, created_at, updated_at
FROM campaign WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id int64) (*Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Name,
		&i.Budget,
		&i.DailyBudget,
		&i.StartTime,
		&i.EndTime,
		&i.Pacing,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, advertiser_id, name, budget, daily_budget, start_time, end_time, pacing, status, version, created_at, updated_at
FROM campaign WHERE advertiser_id = $1
  AND ($4::smallint IS NULL OR status = $4::smallint)
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListCampaignsParams struct {
	AdvertiserID int64  `json:"advertiser_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	Status       *int16 `json:"status"`
}

func (q *Queries) ListCampaigns(ctx context.Context, arg *ListCampaignsParams) ([]*Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns,
		arg.AdvertiserID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Name,
			&i.Budget,
			&i.DailyBudget,
			&i.StartTime,
			&i.EndTime,
			&i.Pacing,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaign SET name=$1, budget=$2, daily_budget=$3, start_time=$4, end_time=$5, pacing=$6, version=version+1, updated_at=$7
WHERE id=$8 AND version=$9
RETURNING version
`

type UpdateCampaignParams struct {
	Name        string             `json:"name"`
	Budget      pgtype.Numeric     `json:"budget"`
	DailyBudget pgtype.Numeric     `json:"daily_budget"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Pacing      *int16             `json:"pacing"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          int64              `json:"id"`
	Version     *int64             `json:"version"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg *UpdateCampaignParams) (*int64, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.Name,
		arg.Budget,
		arg.DailyBudget,
		arg.StartTime,
		arg.EndTime,
		arg.Pacing,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	var version *int64
	err := row.Scan(&version)
	return version, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :exec
UPDATE campaign SET status=$1, version=version+1, updated_at=NOW() WHERE id=$2
`

type UpdateCampaignStatusParams struct {
	Status *int16 `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg *UpdateCampaignStatusParams) error {
	_, err := q.db.Exec(ctx, updateCampaignStatus, arg.Status, arg.ID)
	return err
}
