// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: creative.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCreativesByAdGroup = `-- name: CountCreativesByAdGroup :one
SELECT COUNT(*) FROM creative WHERE ($1::bigint IS NULL OR ad_group_id = $1::bigint) AND is_valid = 1
`

func (q *Queries) CountCreativesByAdGroup(ctx context.Context, adGroupID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCreativesByAdGroup, adGroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCreative = `-- name: CreateCreative :one
INSERT INTO creative (ad_group_id, name, creative_type, asset_url, asset_size, asset_duration, asset_width, asset_height, asset_mime,
  title, description, cta_text, brand_name, brand_logo, landing_url, deeplink_url, imp_tracker, click_tracker, third_party_trackers)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)
RETURNING id, version, created_at, updated_at
`

type CreateCreativeParams struct {
	AdGroupID          int64   `json:"ad_group_id"`
	Name               string  `json:"name"`
	CreativeType       int16   `json:"creative_type"`
	AssetUrl           string  `json:"asset_url"`
	AssetSize          *int32  `json:"asset_size"`
	AssetDuration      *int32  `json:"asset_duration"`
	AssetWidth         *int32  `json:"asset_width"`
	AssetHeight        *int32  `json:"asset_height"`
	AssetMime          *string `json:"asset_mime"`
	Title              *string `json:"title"`
	Description        *string `json:"description"`
	CtaText            *string `json:"cta_text"`
	BrandName          *string `json:"brand_name"`
	BrandLogo          *string `json:"brand_logo"`
	LandingUrl         string  `json:"landing_url"`
	DeeplinkUrl        *string `json:"deeplink_url"`
	ImpTracker         *string `json:"imp_tracker"`
	ClickTracker       *string `json:"click_tracker"`
	ThirdPartyTrackers []byte  `json:"third_party_trackers"`
}

type CreateCreativeRow struct {
	ID        int64              `json:"id"`
	Version   *int64             `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCreative(ctx context.Context, arg *CreateCreativeParams) (*CreateCreativeRow, error) {
	row := q.db.QueryRow(ctx, createCreative,
		arg.AdGroupID,
		arg.Name,
		arg.CreativeType,
		arg.AssetUrl,
		arg.AssetSize,
		arg.AssetDuration,
		arg.AssetWidth,
		arg.AssetHeight,
		arg.AssetMime,
		arg.Title,
		arg.Description,
		arg.CtaText,
		arg.BrandName,
		arg.BrandLogo,
		arg.LandingUrl,
		arg.DeeplinkUrl,
		arg.ImpTracker,
		arg.ClickTracker,
		arg.ThirdPartyTrackers,
	)
	var i CreateCreativeRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listApprovedCreativesByAdGroup = `-- name: ListApprovedCreativesByAdGroup :many
SELECT id, ad_group_id, name, creative_type, asset_url, asset_size, asset_duration, asset_width, asset_height, asset_mime,
  title, description, cta_text, brand_name, brand_logo, landing_url, deeplink_url, imp_tracker, click_tracker, third_party_trackers,
  audit_status
FROM creative WHERE ad_group_id = $1 AND audit_status = $2 AND is_valid = 1
`

type ListApprovedCreativesByAdGroupParams struct {
	AdGroupID   int64  `json:"ad_group_id"`
	AuditStatus *int16 `json:"audit_status"`
}

type ListApprovedCreativesByAdGroupRow struct {
	ID                 int64   `json:"id"`
	AdGroupID          int64   `json:"ad_group_id"`
	Name               string  `json:"name"`
	CreativeType       int16   `json:"creative_type"`
	AssetUrl           string  `json:"asset_url"`
	AssetSize          *int32  `json:"asset_size"`
	AssetDuration      *int32  `json:"asset_duration"`
	AssetWidth         *int32  `json:"asset_width"`
	AssetHeight        *int32  `json:"asset_height"`
	AssetMime          *string `json:"asset_mime"`
	Title              *string `json:"title"`
	Description        *string `json:"description"`
	CtaText            *string `json:"cta_text"`
	BrandName          *string `json:"brand_name"`
	BrandLogo          *string `json:"brand_logo"`
	LandingUrl         string  `json:"landing_url"`
	DeeplinkUrl        *string `json:"deeplink_url"`
	ImpTracker         *string `json:"imp_tracker"`
	ClickTracker       *string `json:"click_tracker"`
	ThirdPartyTrackers []byte  `json:"third_party_trackers"`
	AuditStatus        *int16  `json:"audit_status"`
}

func (q *Queries) ListApprovedCreativesByAdGroup(ctx context.Context, arg *ListApprovedCreativesByAdGroupParams) ([]*ListApprovedCreativesByAdGroupRow, error) {
	rows, err := q.db.Query(ctx, listApprovedCreativesByAdGroup, arg.AdGroupID, arg.AuditStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListApprovedCreativesByAdGroupRow
	for rows.Next() {
		var i ListApprovedCreativesByAdGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.AdGroupID,
			&i.Name,
			&i.CreativeType,
			&i.AssetUrl,
			&i.AssetSize,
			&i.AssetDuration,
			&i.AssetWidth,
			&i.AssetHeight,
			&i.AssetMime,
			&i.Title,
			&i.Description,
			&i.CtaText,
			&i.BrandName,
			&i.BrandLogo,
			&i.LandingUrl,
			&i.DeeplinkUrl,
			&i.ImpTracker,
			&i.ClickTracker,
			&i.ThirdPartyTrackers,
			&i.AuditStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreativesByAdGroup = `-- name: ListCreativesByAdGroup :many
SELECT id, ad_group_id, name, creative_type, asset_url, asset_size, asset_duration, asset_width, asset_height, asset_mime,
  title, description, cta_text, brand_name, brand_logo, landing_url, deeplink_url, imp_tracker, click_tracker, third_party_trackers,
  audit_status, audit_reason, version, created_at, updated_at
FROM creative WHERE ($1::bigint IS NULL OR ad_group_id = $1::bigint) AND is_valid = 1
ORDER BY created_at DESC LIMIT $3 OFFSET $2
`

type ListCreativesByAdGroupParams struct {
	AdGroupID *int64 `json:"ad_group_id"`
	Offset    int32  `json:"offset"`
	Limit     int32  `json:"limit"`
}

type ListCreativesByAdGroupRow struct {
	ID                 int64              `json:"id"`
	AdGroupID          int64              `json:"ad_group_id"`
	Name               string             `json:"name"`
	CreativeType       int16              `json:"creative_type"`
	AssetUrl           string             `json:"asset_url"`
	AssetSize          *int32             `json:"asset_size"`
	AssetDuration      *int32             `json:"asset_duration"`
	AssetWidth         *int32             `json:"asset_width"`
	AssetHeight        *int32             `json:"asset_height"`
	AssetMime          *string            `json:"asset_mime"`
	Title              *string            `json:"title"`
	Description        *string            `json:"description"`
	CtaText            *string            `json:"cta_text"`
	BrandName          *string            `json:"brand_name"`
	BrandLogo          *string            `json:"brand_logo"`
	LandingUrl         string             `json:"landing_url"`
	DeeplinkUrl        *string            `json:"deeplink_url"`
	ImpTracker         *string            `json:"imp_tracker"`
	ClickTracker       *string            `json:"click_tracker"`
	ThirdPartyTrackers []byte             `json:"third_party_trackers"`
	AuditStatus        *int16             `json:"audit_status"`
	AuditReason        *string            `json:"audit_reason"`
	Version            *int64             `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCreativesByAdGroup(ctx context.Context, arg *ListCreativesByAdGroupParams) ([]*ListCreativesByAdGroupRow, error) {
	rows, err := q.db.Query(ctx, listCreativesByAdGroup, arg.AdGroupID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCreativesByAdGroupRow
	for rows.Next() {
		var i ListCreativesByAdGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.AdGroupID,
			&i.Name,
			&i.CreativeType,
			&i.AssetUrl,
			&i.AssetSize,
			&i.AssetDuration,
			&i.AssetWidth,
			&i.AssetHeight,
			&i.AssetMime,
			&i.Title,
			&i.Description,
			&i.CtaText,
			&i.BrandName,
			&i.BrandLogo,
			&i.LandingUrl,
			&i.DeeplinkUrl,
			&i.ImpTracker,
			&i.ClickTracker,
			&i.ThirdPartyTrackers,
			&i.AuditStatus,
			&i.AuditReason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitCreativeAudit = `-- name: SubmitCreativeAudit :exec
UPDATE creative SET audit_status = $1, version = version + 1, updated_at = NOW() WHERE id = $2
`

type SubmitCreativeAuditParams struct {
	AuditStatus *int16 `json:"audit_status"`
	ID          int64  `json:"id"`
}

func (q *Queries) SubmitCreativeAudit(ctx context.Context, arg *SubmitCreativeAuditParams) error {
	_, err := q.db.Exec(ctx, submitCreativeAudit, arg.AuditStatus, arg.ID)
	return err
}

const updateCreative = `-- name: UpdateCreative :exec
UPDATE creative SET name=$1, asset_url=$2, asset_width=$3, asset_height=$4, asset_duration=$5,
  title=$6, description=$7, landing_url=$8, imp_tracker=$9, click_tracker=$10,
  version=version+1, updated_at=NOW()
WHERE id=$11 AND version=$12
`

type UpdateCreativeParams struct {
	Name          string  `json:"name"`
	AssetUrl      string  `json:"asset_url"`
	AssetWidth    *int32  `json:"asset_width"`
	AssetHeight   *int32  `json:"asset_height"`
	AssetDuration *int32  `json:"asset_duration"`
	Title         *string `json:"title"`
	Description   *string `json:"description"`
	LandingUrl    string  `json:"landing_url"`
	ImpTracker    *string `json:"imp_tracker"`
	ClickTracker  *string `json:"click_tracker"`
	ID            int64   `json:"id"`
	Version       *int64  `json:"version"`
}

func (q *Queries) UpdateCreative(ctx context.Context, arg *UpdateCreativeParams) error {
	_, err := q.db.Exec(ctx, updateCreative,
		arg.Name,
		arg.AssetUrl,
		arg.AssetWidth,
		arg.AssetHeight,
		arg.AssetDuration,
		arg.Title,
		arg.Description,
		arg.LandingUrl,
		arg.ImpTracker,
		arg.ClickTracker,
		arg.ID,
		arg.Version,
	)
	return err
}

const updateCreativeAuditStatus = `-- name: UpdateCreativeAuditStatus :exec
UPDATE creative SET audit_status = $1, audit_reason = $2, version = version + 1, updated_at = NOW() WHERE id = $3
`

type UpdateCreativeAuditStatusParams struct {
	AuditStatus *int16  `json:"audit_status"`
	AuditReason *string `json:"audit_reason"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateCreativeAuditStatus(ctx context.Context, arg *UpdateCreativeAuditStatusParams) error {
	_, err := q.db.Exec(ctx, updateCreativeAuditStatus, arg.AuditStatus, arg.AuditReason, arg.ID)
	return err
}
