// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dmp.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAudience = `-- name: CreateAudience :one
INSERT INTO dmp_audience (advertiser_id, name, audience_type, rules, status)
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateAudienceParams struct {
	AdvertiserID int64  `json:"advertiser_id"`
	Name         string `json:"name"`
	AudienceType *int16 `json:"audience_type"`
	Rules        []byte `json:"rules"`
	Status       *int16 `json:"status"`
}

func (q *Queries) CreateAudience(ctx context.Context, arg *CreateAudienceParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAudience,
		arg.AdvertiserID,
		arg.Name,
		arg.AudienceType,
		arg.Rules,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO dmp_tag (advertiser_id, name, tag_type, source, source_config, status)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type CreateTagParams struct {
	AdvertiserID int64   `json:"advertiser_id"`
	Name         string  `json:"name"`
	TagType      int16   `json:"tag_type"`
	Source       *string `json:"source"`
	SourceConfig []byte  `json:"source_config"`
	Status       *int16  `json:"status"`
}

func (q *Queries) CreateTag(ctx context.Context, arg *CreateTagParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.AdvertiserID,
		arg.Name,
		arg.TagType,
		arg.Source,
		arg.SourceConfig,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAudience = `-- name: DeleteAudience :exec
DELETE FROM dmp_audience WHERE id = $1
`

func (q *Queries) DeleteAudience(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAudience, id)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM dmp_tag WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getAudience = `-- name: GetAudience :one
SELECT id, advertiser_id, name, audience_type, rules, device_count, status, created_at
FROM dmp_audience WHERE id = $1
`

type GetAudienceRow struct {
	ID           int64              `json:"id"`
	AdvertiserID int64              `json:"advertiser_id"`
	Name         string             `json:"name"`
	AudienceType *int16             `json:"audience_type"`
	Rules        []byte             `json:"rules"`
	DeviceCount  *int64             `json:"device_count"`
	Status       *int16             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAudience(ctx context.Context, id int64) (*GetAudienceRow, error) {
	row := q.db.QueryRow(ctx, getAudience, id)
	var i GetAudienceRow
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Name,
		&i.AudienceType,
		&i.Rules,
		&i.DeviceCount,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const getDeviceTags = `-- name: GetDeviceTags :one
SELECT tag_ids FROM dmp_device WHERE device_id = $1 AND device_type = $2
`

type GetDeviceTagsParams struct {
	DeviceID   string `json:"device_id"`
	DeviceType string `json:"device_type"`
}

func (q *Queries) GetDeviceTags(ctx context.Context, arg *GetDeviceTagsParams) ([]int64, error) {
	row := q.db.QueryRow(ctx, getDeviceTags, arg.DeviceID, arg.DeviceType)
	var tag_ids []int64
	err := row.Scan(&tag_ids)
	return tag_ids, err
}

const getTag = `-- name: GetTag :one
SELECT id, advertiser_id, name, tag_type, device_count, source, source_config, status, created_at
FROM dmp_tag WHERE id = $1
`

type GetTagRow struct {
	ID           int64              `json:"id"`
	AdvertiserID int64              `json:"advertiser_id"`
	Name         string             `json:"name"`
	TagType      int16              `json:"tag_type"`
	DeviceCount  *int64             `json:"device_count"`
	Source       *string            `json:"source"`
	SourceConfig []byte             `json:"source_config"`
	Status       *int16             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetTag(ctx context.Context, id int64) (*GetTagRow, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i GetTagRow
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Name,
		&i.TagType,
		&i.DeviceCount,
		&i.Source,
		&i.SourceConfig,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const listAudiences = `-- name: ListAudiences :many
SELECT id, advertiser_id, name, audience_type, rules, device_count, status, created_at
FROM dmp_audience WHERE advertiser_id = $1 AND ($2::smallint IS NULL OR audience_type = $2)
ORDER BY created_at DESC
`

type ListAudiencesParams struct {
	AdvertiserID int64 `json:"advertiser_id"`
	Column2      int16 `json:"column_2"`
}

type ListAudiencesRow struct {
	ID           int64              `json:"id"`
	AdvertiserID int64              `json:"advertiser_id"`
	Name         string             `json:"name"`
	AudienceType *int16             `json:"audience_type"`
	Rules        []byte             `json:"rules"`
	DeviceCount  *int64             `json:"device_count"`
	Status       *int16             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAudiences(ctx context.Context, arg *ListAudiencesParams) ([]*ListAudiencesRow, error) {
	rows, err := q.db.Query(ctx, listAudiences, arg.AdvertiserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAudiencesRow
	for rows.Next() {
		var i ListAudiencesRow
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Name,
			&i.AudienceType,
			&i.Rules,
			&i.DeviceCount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, advertiser_id, name, tag_type, device_count, source, status, created_at
FROM dmp_tag WHERE advertiser_id = $1 AND ($2::smallint IS NULL OR tag_type = $2)
ORDER BY created_at DESC
`

type ListTagsParams struct {
	AdvertiserID int64 `json:"advertiser_id"`
	Column2      int16 `json:"column_2"`
}

type ListTagsRow struct {
	ID           int64              `json:"id"`
	AdvertiserID int64              `json:"advertiser_id"`
	Name         string             `json:"name"`
	TagType      int16              `json:"tag_type"`
	DeviceCount  *int64             `json:"device_count"`
	Source       *string            `json:"source"`
	Status       *int16             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTags(ctx context.Context, arg *ListTagsParams) ([]*ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, arg.AdvertiserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Name,
			&i.TagType,
			&i.DeviceCount,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAudienceDeviceCount = `-- name: UpdateAudienceDeviceCount :exec
UPDATE dmp_audience SET device_count = $2, status = $3, updated_at = NOW() WHERE id = $1
`

type UpdateAudienceDeviceCountParams struct {
	ID          int64  `json:"id"`
	DeviceCount *int64 `json:"device_count"`
	Status      *int16 `json:"status"`
}

func (q *Queries) UpdateAudienceDeviceCount(ctx context.Context, arg *UpdateAudienceDeviceCountParams) error {
	_, err := q.db.Exec(ctx, updateAudienceDeviceCount, arg.ID, arg.DeviceCount, arg.Status)
	return err
}

const updateTagDeviceCount = `-- name: UpdateTagDeviceCount :exec
UPDATE dmp_tag SET device_count = $2, status = $3, updated_at = NOW() WHERE id = $1
`

type UpdateTagDeviceCountParams struct {
	ID          int64  `json:"id"`
	DeviceCount *int64 `json:"device_count"`
	Status      *int16 `json:"status"`
}

func (q *Queries) UpdateTagDeviceCount(ctx context.Context, arg *UpdateTagDeviceCountParams) error {
	_, err := q.db.Exec(ctx, updateTagDeviceCount, arg.ID, arg.DeviceCount, arg.Status)
	return err
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO dmp_device (device_id, device_type, tag_ids, last_seen)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (device_id, device_type) DO UPDATE SET
    tag_ids = dmp_device.tag_ids || EXCLUDED.tag_ids,
    last_seen = NOW()
`

type UpsertDeviceParams struct {
	DeviceID   string  `json:"device_id"`
	DeviceType string  `json:"device_type"`
	TagIds     []int64 `json:"tag_ids"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg *UpsertDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertDevice, arg.DeviceID, arg.DeviceType, arg.TagIds)
	return err
}
