// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: filegateway.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFileRecord = `-- name: DeleteFileRecord :exec
UPDATE file_record SET status = 3, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteFileRecord(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFileRecord, id)
	return err
}

const getFileRecord = `-- name: GetFileRecord :one
SELECT id, namespace, storage_key, filename, size, content_type, md5, status, created_at
FROM file_record WHERE id = $1
`

type GetFileRecordRow struct {
	ID          string             `json:"id"`
	Namespace   string             `json:"namespace"`
	StorageKey  string             `json:"storage_key"`
	Filename    *string            `json:"filename"`
	Size        *int64             `json:"size"`
	ContentType *string            `json:"content_type"`
	Md5         *string            `json:"md5"`
	Status      *int16             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetFileRecord(ctx context.Context, id string) (*GetFileRecordRow, error) {
	row := q.db.QueryRow(ctx, getFileRecord, id)
	var i GetFileRecordRow
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.StorageKey,
		&i.Filename,
		&i.Size,
		&i.ContentType,
		&i.Md5,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const insertFileRecord = `-- name: InsertFileRecord :exec
INSERT INTO file_record (id, namespace, storage_key, filename, size, content_type, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertFileRecordParams struct {
	ID          string  `json:"id"`
	Namespace   string  `json:"namespace"`
	StorageKey  string  `json:"storage_key"`
	Filename    *string `json:"filename"`
	Size        *int64  `json:"size"`
	ContentType *string `json:"content_type"`
	Status      *int16  `json:"status"`
}

func (q *Queries) InsertFileRecord(ctx context.Context, arg *InsertFileRecordParams) error {
	_, err := q.db.Exec(ctx, insertFileRecord,
		arg.ID,
		arg.Namespace,
		arg.StorageKey,
		arg.Filename,
		arg.Size,
		arg.ContentType,
		arg.Status,
	)
	return err
}

const updateFileRecordReady = `-- name: UpdateFileRecordReady :exec
UPDATE file_record SET status = 2, size = $2, content_type = $3, md5 = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateFileRecordReadyParams struct {
	ID          string  `json:"id"`
	Size        *int64  `json:"size"`
	ContentType *string `json:"content_type"`
	Md5         *string `json:"md5"`
}

func (q *Queries) UpdateFileRecordReady(ctx context.Context, arg *UpdateFileRecordReadyParams) error {
	_, err := q.db.Exec(ctx, updateFileRecordReady,
		arg.ID,
		arg.Size,
		arg.ContentType,
		arg.Md5,
	)
	return err
}
