// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fraud.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFraudEvents = `-- name: CountFraudEvents :one
SELECT COUNT(*) FROM fraud_events
WHERE created_at >= $1 AND created_at <= $2
`

type CountFraudEventsParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) CountFraudEvents(ctx context.Context, arg *CountFraudEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFraudEvents, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFraudEventStats = `-- name: GetFraudEventStats :one
SELECT
    COUNT(*)::bigint as total,
    COUNT(*) FILTER (WHERE action = 'blocked')::bigint as blocked,
    COUNT(*) FILTER (WHERE action = 'flagged')::bigint as flagged
FROM fraud_events
WHERE created_at >= $1 AND created_at <= $2
`

type GetFraudEventStatsParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetFraudEventStatsRow struct {
	Total   int64 `json:"total"`
	Blocked int64 `json:"blocked"`
	Flagged int64 `json:"flagged"`
}

func (q *Queries) GetFraudEventStats(ctx context.Context, arg *GetFraudEventStatsParams) (*GetFraudEventStatsRow, error) {
	row := q.db.QueryRow(ctx, getFraudEventStats, arg.CreatedAt, arg.CreatedAt_2)
	var i GetFraudEventStatsRow
	err := row.Scan(&i.Total, &i.Blocked, &i.Flagged)
	return &i, err
}

const insertFraudEvent = `-- name: InsertFraudEvent :exec

INSERT INTO fraud_events (request_id, rule_type, rule_value, risk_score, action, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertFraudEventParams struct {
	RequestID string         `json:"request_id"`
	RuleType  string         `json:"rule_type"`
	RuleValue string         `json:"rule_value"`
	RiskScore pgtype.Numeric `json:"risk_score"`
	Action    string         `json:"action"`
	CreatedAt time.Time      `json:"created_at"`
}

// Fraud events queries
func (q *Queries) InsertFraudEvent(ctx context.Context, arg *InsertFraudEventParams) error {
	_, err := q.db.Exec(ctx, insertFraudEvent,
		arg.RequestID,
		arg.RuleType,
		arg.RuleValue,
		arg.RiskScore,
		arg.Action,
		arg.CreatedAt,
	)
	return err
}

const listFraudEvents = `-- name: ListFraudEvents :many
SELECT id, request_id, rule_type, rule_value, COALESCE(risk_score, 0) as risk_score, action, created_at
FROM fraud_events
WHERE created_at >= $1 AND created_at <= $2
ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListFraudEventsParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type ListFraudEventsRow struct {
	ID        int64     `json:"id"`
	RequestID string    `json:"request_id"`
	RuleType  string    `json:"rule_type"`
	RuleValue string    `json:"rule_value"`
	RiskScore float64   `json:"risk_score"`
	Action    string    `json:"action"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListFraudEvents(ctx context.Context, arg *ListFraudEventsParams) ([]*ListFraudEventsRow, error) {
	rows, err := q.db.Query(ctx, listFraudEvents,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListFraudEventsRow
	for rows.Next() {
		var i ListFraudEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.RuleType,
			&i.RuleValue,
			&i.RiskScore,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
