// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdGroup struct {
	ID          int64              `json:"id"`
	CampaignID  int64              `json:"campaign_id"`
	Name        string             `json:"name"`
	BidType     int16              `json:"bid_type"`
	BidPrice    float64            `json:"bid_price"`
	DailyBudget pgtype.Numeric     `json:"daily_budget"`
	FreqCap     *int32             `json:"freq_cap"`
	FreqPeriod  *int32             `json:"freq_period"`
	Targeting   json.RawMessage    `json:"targeting"`
	Status      *int16             `json:"status"`
	Version     *int64             `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AdPosition struct {
	ID           int64              `json:"id"`
	MediaID      int64              `json:"media_id"`
	Name         string             `json:"name"`
	PositionType int16              `json:"position_type"`
	AdFormat     int16              `json:"ad_format"`
	Width        *int32             `json:"width"`
	Height       *int32             `json:"height"`
	MaxSize      *int32             `json:"max_size"`
	DurationMin  *int32             `json:"duration_min"`
	DurationMax  *int32             `json:"duration_max"`
	MimeTypes    *string            `json:"mime_types"`
	Status       *int16             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AdPositionPrice struct {
	ID           int64              `json:"id"`
	AdPositionID int64              `json:"ad_position_id"`
	ChargeType   int16              `json:"charge_type"`
	FloorPrice   float64            `json:"floor_price"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Advertiser struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	Industry            *string            `json:"industry"`
	ContactName         *string            `json:"contact_name"`
	ContactEmail        *string            `json:"contact_email"`
	Balance             pgtype.Numeric     `json:"balance"`
	Status              *int16             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	QualificationStatus *int16             `json:"qualification_status"`
	QualificationReason *string            `json:"qualification_reason"`
	CreditLimit         pgtype.Numeric     `json:"credit_limit"`
	Address             *string            `json:"address"`
	Website             *string            `json:"website"`
	BrandNames          *string            `json:"brand_names"`
}

// Multi-platform advertiser synchronization status
type AdvertiserSync struct {
	ID           int64              `json:"id"`
	AdvertiserID int64              `json:"advertiser_id"`
	Platform     string             `json:"platform"`
	Status       int16              `json:"status"`
	ExternalAdID *string            `json:"external_ad_id"`
	Reason       *string            `json:"reason"`
	RawResponse  []byte             `json:"raw_response"`
	SyncedAt     pgtype.Timestamptz `json:"synced_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type BalanceTransaction struct {
	ID            int64              `json:"id"`
	AdvertiserID  int64              `json:"advertiser_id"`
	Amount        float64            `json:"amount"`
	BalanceBefore float64            `json:"balance_before"`
	BalanceAfter  float64            `json:"balance_after"`
	TxType        int16              `json:"tx_type"`
	Description   *string            `json:"description"`
	OperatorID    *int64             `json:"operator_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Campaign struct {
	ID           int64              `json:"id"`
	AdvertiserID int64              `json:"advertiser_id"`
	Name         string             `json:"name"`
	Budget       pgtype.Numeric     `json:"budget"`
	DailyBudget  pgtype.Numeric     `json:"daily_budget"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	EndTime      pgtype.Timestamptz `json:"end_time"`
	Pacing       *int16             `json:"pacing"`
	Status       *int16             `json:"status"`
	Version      *int64             `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ContentTarget struct {
	ID           int64              `json:"id"`
	MediaID      int64              `json:"media_id"`
	ContentID    string             `json:"content_id"`
	ContentTitle *string            `json:"content_title"`
	ContentUrl   *string            `json:"content_url"`
	ContentType  *int16             `json:"content_type"`
	Category     *string            `json:"category"`
	Tags         *string            `json:"tags"`
	Duration     *int32             `json:"duration"`
	StartTime    *int32             `json:"start_time"`
	SlotDuration *int32             `json:"slot_duration"`
	SlotID       *string            `json:"slot_id"`
	Ext          []byte             `json:"ext"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ConversionEvent struct {
	ID           int64              `json:"id"`
	ClickID      string             `json:"click_id"`
	EventType    string             `json:"event_type"`
	AdgroupID    *int64             `json:"adgroup_id"`
	CreativeID   *int64             `json:"creative_id"`
	CampaignID   *int64             `json:"campaign_id"`
	AdvertiserID *int64             `json:"advertiser_id"`
	MediaID      *int64             `json:"media_id"`
	AdPositionID *int64             `json:"ad_position_id"`
	Price        pgtype.Numeric     `json:"price"`
	Revenue      pgtype.Numeric     `json:"revenue"`
	DeviceID     *string            `json:"device_id"`
	Ip           *string            `json:"ip"`
	Ua           *string            `json:"ua"`
	GeoCity      *string            `json:"geo_city"`
	Extra        []byte             `json:"extra"`
	EventTime    time.Time          `json:"event_time"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Creative struct {
	ID                 int64              `json:"id"`
	AdGroupID          int64              `json:"ad_group_id"`
	Name               string             `json:"name"`
	CreativeType       int16              `json:"creative_type"`
	AssetUrl           string             `json:"asset_url"`
	AssetSize          *int32             `json:"asset_size"`
	AssetDuration      *int32             `json:"asset_duration"`
	AssetWidth         *int32             `json:"asset_width"`
	AssetHeight        *int32             `json:"asset_height"`
	AssetMime          *string            `json:"asset_mime"`
	Title              *string            `json:"title"`
	Description        *string            `json:"description"`
	CtaText            *string            `json:"cta_text"`
	BrandName          *string            `json:"brand_name"`
	BrandLogo          *string            `json:"brand_logo"`
	LandingUrl         string             `json:"landing_url"`
	DeeplinkUrl        *string            `json:"deeplink_url"`
	ImpTracker         *string            `json:"imp_tracker"`
	ClickTracker       *string            `json:"click_tracker"`
	ThirdPartyTrackers []byte             `json:"third_party_trackers"`
	AuditStatus        *int16             `json:"audit_status"`
	AuditReason        *string            `json:"audit_reason"`
	IsValid            *int16             `json:"is_valid"`
	Version            *int64             `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// Multi-platform creative synchronization status
type CreativeSync struct {
	ID           int64              `json:"id"`
	CreativeID   int64              `json:"creative_id"`
	Platform     string             `json:"platform"`
	Status       int16              `json:"status"`
	ExternalID   *string            `json:"external_id"`
	ExternalTvid *string            `json:"external_tvid"`
	Reason       *string            `json:"reason"`
	RawResponse  []byte             `json:"raw_response"`
	SyncedAt     pgtype.Timestamptz `json:"synced_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DmpAudience struct {
	ID           int64              `json:"id"`
	AdvertiserID int64              `json:"advertiser_id"`
	Name         string             `json:"name"`
	AudienceType *int16             `json:"audience_type"`
	DeviceCount  *int64             `json:"device_count"`
	Rules        []byte             `json:"rules"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Status       *int16             `json:"status"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DmpDevice struct {
	DeviceID   string             `json:"device_id"`
	DeviceType string             `json:"device_type"`
	TagIds     []int64            `json:"tag_ids"`
	FirstSeen  pgtype.Timestamptz `json:"first_seen"`
	LastSeen   pgtype.Timestamptz `json:"last_seen"`
}

type DmpTag struct {
	ID           int64              `json:"id"`
	AdvertiserID int64              `json:"advertiser_id"`
	Name         string             `json:"name"`
	TagType      int16              `json:"tag_type"`
	DeviceCount  *int64             `json:"device_count"`
	Source       *string            `json:"source"`
	SourceConfig []byte             `json:"source_config"`
	Status       *int16             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type FileRecord struct {
	ID          string             `json:"id"`
	Namespace   string             `json:"namespace"`
	StorageKey  string             `json:"storage_key"`
	Filename    *string            `json:"filename"`
	Size        *int64             `json:"size"`
	ContentType *string            `json:"content_type"`
	Md5         *string            `json:"md5"`
	Status      *int16             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Medium struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Code      string             `json:"code"`
	Domain    *string            `json:"domain"`
	Status    *int16             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProofMaterial struct {
	ID           int64              `json:"id"`
	AdvertiserID int64              `json:"advertiser_id"`
	MaterialType int16              `json:"material_type"`
	FileUrl      string             `json:"file_url"`
	FileName     *string            `json:"file_name"`
	FileSize     *int32             `json:"file_size"`
	AuditStatus  *int16             `json:"audit_status"`
	AuditReason  *string            `json:"audit_reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ReportHourly struct {
	ID           int64          `json:"id"`
	Hour         time.Time      `json:"hour"`
	AdvertiserID int64          `json:"advertiser_id"`
	CampaignID   int64          `json:"campaign_id"`
	AdGroupID    int64          `json:"ad_group_id"`
	CreativeID   int64          `json:"creative_id"`
	MediaID      int64          `json:"media_id"`
	AdPositionID int64          `json:"ad_position_id"`
	Impressions  *int64         `json:"impressions"`
	Clicks       *int64         `json:"clicks"`
	Conversions  *int64         `json:"conversions"`
	Cost         pgtype.Numeric `json:"cost"`
	WinCount     *int64         `json:"win_count"`
	BidCount     *int64         `json:"bid_count"`
	Revenue      pgtype.Numeric `json:"revenue"`
}

type StatEvent struct {
	ID           *int64             `json:"id"`
	EventType    int16              `json:"event_type"`
	AdgroupID    int64              `json:"adgroup_id"`
	CreativeID   int64              `json:"creative_id"`
	CampaignID   int64              `json:"campaign_id"`
	AdvertiserID int64              `json:"advertiser_id"`
	MediaID      int64              `json:"media_id"`
	AdPositionID int64              `json:"ad_position_id"`
	Price        pgtype.Numeric     `json:"price"`
	ChargeType   *int16             `json:"charge_type"`
	DeviceID     *string            `json:"device_id"`
	Ip           *string            `json:"ip"`
	Ua           *string            `json:"ua"`
	GeoCity      *string            `json:"geo_city"`
	FreqResult   *string            `json:"freq_result"`
	EventTime    time.Time          `json:"event_time"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ClickID      *string            `json:"click_id"`
}

type StatEvent202506 struct {
	ID           *int64             `json:"id"`
	EventType    int16              `json:"event_type"`
	AdgroupID    int64              `json:"adgroup_id"`
	CreativeID   int64              `json:"creative_id"`
	CampaignID   int64              `json:"campaign_id"`
	AdvertiserID int64              `json:"advertiser_id"`
	MediaID      int64              `json:"media_id"`
	AdPositionID int64              `json:"ad_position_id"`
	Price        pgtype.Numeric     `json:"price"`
	ChargeType   *int16             `json:"charge_type"`
	DeviceID     *string            `json:"device_id"`
	Ip           *string            `json:"ip"`
	Ua           *string            `json:"ua"`
	GeoCity      *string            `json:"geo_city"`
	FreqResult   *string            `json:"freq_result"`
	EventTime    time.Time          `json:"event_time"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         *string            `json:"name"`
	AdvertiserID *int64             `json:"advertiser_id"`
	Role         *string            `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
