// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_sync.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdvertiserSync = `-- name: GetAdvertiserSync :one
SELECT id, advertiser_id, platform, status, external_ad_id, reason, raw_response, synced_at, created_at, updated_at
FROM advertiser_sync WHERE advertiser_id = $1 AND platform = $2
`

type GetAdvertiserSyncParams struct {
	AdvertiserID int64  `json:"advertiser_id"`
	Platform     string `json:"platform"`
}

func (q *Queries) GetAdvertiserSync(ctx context.Context, arg *GetAdvertiserSyncParams) (*AdvertiserSync, error) {
	row := q.db.QueryRow(ctx, getAdvertiserSync, arg.AdvertiserID, arg.Platform)
	var i AdvertiserSync
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Platform,
		&i.Status,
		&i.ExternalAdID,
		&i.Reason,
		&i.RawResponse,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCreativeSync = `-- name: GetCreativeSync :one
SELECT id, creative_id, platform, status, external_id, external_tvid, reason, raw_response, synced_at, created_at, updated_at
FROM creative_sync WHERE creative_id = $1 AND platform = $2
`

type GetCreativeSyncParams struct {
	CreativeID int64  `json:"creative_id"`
	Platform   string `json:"platform"`
}

func (q *Queries) GetCreativeSync(ctx context.Context, arg *GetCreativeSyncParams) (*CreativeSync, error) {
	row := q.db.QueryRow(ctx, getCreativeSync, arg.CreativeID, arg.Platform)
	var i CreativeSync
	err := row.Scan(
		&i.ID,
		&i.CreativeID,
		&i.Platform,
		&i.Status,
		&i.ExternalID,
		&i.ExternalTvid,
		&i.Reason,
		&i.RawResponse,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listApprovedCreativeSync = `-- name: ListApprovedCreativeSync :many
SELECT cs.creative_id, cs.platform, cs.external_tvid
FROM creative_sync cs
WHERE cs.status = 3
`

type ListApprovedCreativeSyncRow struct {
	CreativeID   int64   `json:"creative_id"`
	Platform     string  `json:"platform"`
	ExternalTvid *string `json:"external_tvid"`
}

func (q *Queries) ListApprovedCreativeSync(ctx context.Context) ([]*ListApprovedCreativeSyncRow, error) {
	rows, err := q.db.Query(ctx, listApprovedCreativeSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListApprovedCreativeSyncRow
	for rows.Next() {
		var i ListApprovedCreativeSyncRow
		if err := rows.Scan(&i.CreativeID, &i.Platform, &i.ExternalTvid); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAdvertiserSync = `-- name: ListPendingAdvertiserSync :many
SELECT ads.id, ads.advertiser_id, ads.platform, ads.status, ads.external_ad_id, ads.reason,
       adv.name, adv.industry
FROM advertiser_sync ads
JOIN advertiser adv ON ads.advertiser_id = adv.id
WHERE ads.platform = $1 AND ads.status IN (1, 2)
`

type ListPendingAdvertiserSyncRow struct {
	ID           int64   `json:"id"`
	AdvertiserID int64   `json:"advertiser_id"`
	Platform     string  `json:"platform"`
	Status       int16   `json:"status"`
	ExternalAdID *string `json:"external_ad_id"`
	Reason       *string `json:"reason"`
	Name         string  `json:"name"`
	Industry     *string `json:"industry"`
}

func (q *Queries) ListPendingAdvertiserSync(ctx context.Context, platform string) ([]*ListPendingAdvertiserSyncRow, error) {
	rows, err := q.db.Query(ctx, listPendingAdvertiserSync, platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPendingAdvertiserSyncRow
	for rows.Next() {
		var i ListPendingAdvertiserSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Platform,
			&i.Status,
			&i.ExternalAdID,
			&i.Reason,
			&i.Name,
			&i.Industry,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCreativeSync = `-- name: ListPendingCreativeSync :many
SELECT cs.id, cs.creative_id, cs.platform, cs.status, cs.external_id, cs.external_tvid, cs.reason,
       c.asset_url, c.asset_mime, c.asset_width, c.asset_height, c.asset_duration,
       c.title, c.description, c.landing_url, c.deeplink_url, c.imp_tracker, c.click_tracker,
       c.ad_group_id, aig.campaign_id, cam.advertiser_id
FROM creative_sync cs
JOIN creative c ON cs.creative_id = c.id
JOIN ad_group aig ON c.ad_group_id = aig.id
JOIN campaign cam ON aig.campaign_id = cam.id
WHERE cs.platform = $1 AND cs.status IN (1, 2)
`

type ListPendingCreativeSyncRow struct {
	ID            int64   `json:"id"`
	CreativeID    int64   `json:"creative_id"`
	Platform      string  `json:"platform"`
	Status        int16   `json:"status"`
	ExternalID    *string `json:"external_id"`
	ExternalTvid  *string `json:"external_tvid"`
	Reason        *string `json:"reason"`
	AssetUrl      string  `json:"asset_url"`
	AssetMime     *string `json:"asset_mime"`
	AssetWidth    *int32  `json:"asset_width"`
	AssetHeight   *int32  `json:"asset_height"`
	AssetDuration *int32  `json:"asset_duration"`
	Title         *string `json:"title"`
	Description   *string `json:"description"`
	LandingUrl    string  `json:"landing_url"`
	DeeplinkUrl   *string `json:"deeplink_url"`
	ImpTracker    *string `json:"imp_tracker"`
	ClickTracker  *string `json:"click_tracker"`
	AdGroupID     int64   `json:"ad_group_id"`
	CampaignID    int64   `json:"campaign_id"`
	AdvertiserID  int64   `json:"advertiser_id"`
}

func (q *Queries) ListPendingCreativeSync(ctx context.Context, platform string) ([]*ListPendingCreativeSyncRow, error) {
	rows, err := q.db.Query(ctx, listPendingCreativeSync, platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPendingCreativeSyncRow
	for rows.Next() {
		var i ListPendingCreativeSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.CreativeID,
			&i.Platform,
			&i.Status,
			&i.ExternalID,
			&i.ExternalTvid,
			&i.Reason,
			&i.AssetUrl,
			&i.AssetMime,
			&i.AssetWidth,
			&i.AssetHeight,
			&i.AssetDuration,
			&i.Title,
			&i.Description,
			&i.LandingUrl,
			&i.DeeplinkUrl,
			&i.ImpTracker,
			&i.ClickTracker,
			&i.AdGroupID,
			&i.CampaignID,
			&i.AdvertiserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAdvertiserSync = `-- name: UpsertAdvertiserSync :one
INSERT INTO advertiser_sync (advertiser_id, platform, status, external_ad_id, reason, raw_response, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (advertiser_id, platform)
DO UPDATE SET
    status = EXCLUDED.status,
    external_ad_id = COALESCE(EXCLUDED.external_ad_id, advertiser_sync.external_ad_id),
    reason = EXCLUDED.reason,
    raw_response = EXCLUDED.raw_response,
    synced_at = EXCLUDED.synced_at,
    updated_at = NOW()
RETURNING id
`

type UpsertAdvertiserSyncParams struct {
	AdvertiserID int64              `json:"advertiser_id"`
	Platform     string             `json:"platform"`
	Status       int16              `json:"status"`
	ExternalAdID *string            `json:"external_ad_id"`
	Reason       *string            `json:"reason"`
	RawResponse  []byte             `json:"raw_response"`
	SyncedAt     pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) UpsertAdvertiserSync(ctx context.Context, arg *UpsertAdvertiserSyncParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertAdvertiserSync,
		arg.AdvertiserID,
		arg.Platform,
		arg.Status,
		arg.ExternalAdID,
		arg.Reason,
		arg.RawResponse,
		arg.SyncedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertCreativeSync = `-- name: UpsertCreativeSync :one
INSERT INTO creative_sync (creative_id, platform, status, external_id, external_tvid, reason, raw_response, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (creative_id, platform)
DO UPDATE SET
    status = EXCLUDED.status,
    external_id = COALESCE(EXCLUDED.external_id, creative_sync.external_id),
    external_tvid = COALESCE(EXCLUDED.external_tvid, creative_sync.external_tvid),
    reason = EXCLUDED.reason,
    raw_response = EXCLUDED.raw_response,
    synced_at = EXCLUDED.synced_at,
    updated_at = NOW()
RETURNING id
`

type UpsertCreativeSyncParams struct {
	CreativeID   int64              `json:"creative_id"`
	Platform     string             `json:"platform"`
	Status       int16              `json:"status"`
	ExternalID   *string            `json:"external_id"`
	ExternalTvid *string            `json:"external_tvid"`
	Reason       *string            `json:"reason"`
	RawResponse  []byte             `json:"raw_response"`
	SyncedAt     pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) UpsertCreativeSync(ctx context.Context, arg *UpsertCreativeSyncParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertCreativeSync,
		arg.CreativeID,
		arg.Platform,
		arg.Status,
		arg.ExternalID,
		arg.ExternalTvid,
		arg.Reason,
		arg.RawResponse,
		arg.SyncedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
