// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateReportHourly = `-- name: AggregateReportHourly :exec
INSERT INTO report_hourly (hour, advertiser_id, campaign_id, ad_group_id, creative_id, media_id, ad_position_id, impressions, clicks, cost, win_count, bid_count)
SELECT date_trunc('hour', event_time) AS hour,
  advertiser_id, campaign_id, adgroup_id, creative_id, media_id, ad_position_id,
  COUNT(*) FILTER (WHERE event_type = 1 AND freq_result = 'ok') AS impressions,
  COUNT(*) FILTER (WHERE event_type = 2) AS clicks,
  COALESCE(SUM(price) FILTER (WHERE event_type = 1 AND freq_result = 'ok'), 0) AS cost,
  COUNT(*) FILTER (WHERE event_type = 1 AND freq_result = 'ok') AS win_count,
  COUNT(*) FILTER (WHERE event_type = 1) AS bid_count
FROM stat_event
WHERE event_time >= $1 AND event_time < $2
GROUP BY hour, advertiser_id, campaign_id, adgroup_id, creative_id, media_id, ad_position_id
ON CONFLICT (hour, ad_group_id, creative_id, media_id, ad_position_id)
DO UPDATE SET
  impressions = report_hourly.impressions + EXCLUDED.impressions,
  clicks = report_hourly.clicks + EXCLUDED.clicks,
  cost = report_hourly.cost + EXCLUDED.cost,
  win_count = report_hourly.win_count + EXCLUDED.win_count,
  bid_count = report_hourly.bid_count + EXCLUDED.bid_count
`

type AggregateReportHourlyParams struct {
	EventTime   time.Time `json:"event_time"`
	EventTime_2 time.Time `json:"event_time_2"`
}

func (q *Queries) AggregateReportHourly(ctx context.Context, arg *AggregateReportHourlyParams) error {
	_, err := q.db.Exec(ctx, aggregateReportHourly, arg.EventTime, arg.EventTime_2)
	return err
}

const insertStatEvent = `-- name: InsertStatEvent :exec
INSERT INTO stat_event (event_type, adgroup_id, creative_id, campaign_id, advertiser_id, media_id, ad_position_id, price, charge_type, device_id, ip, ua, geo_city, freq_result, click_id, event_time)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
`

type InsertStatEventParams struct {
	EventType    int16          `json:"event_type"`
	AdgroupID    int64          `json:"adgroup_id"`
	CreativeID   int64          `json:"creative_id"`
	CampaignID   int64          `json:"campaign_id"`
	AdvertiserID int64          `json:"advertiser_id"`
	MediaID      int64          `json:"media_id"`
	AdPositionID int64          `json:"ad_position_id"`
	Price        pgtype.Numeric `json:"price"`
	ChargeType   *int16         `json:"charge_type"`
	DeviceID     *string        `json:"device_id"`
	Ip           *string        `json:"ip"`
	Ua           *string        `json:"ua"`
	GeoCity      *string        `json:"geo_city"`
	FreqResult   *string        `json:"freq_result"`
	ClickID      *string        `json:"click_id"`
	EventTime    time.Time      `json:"event_time"`
}

func (q *Queries) InsertStatEvent(ctx context.Context, arg *InsertStatEventParams) error {
	_, err := q.db.Exec(ctx, insertStatEvent,
		arg.EventType,
		arg.AdgroupID,
		arg.CreativeID,
		arg.CampaignID,
		arg.AdvertiserID,
		arg.MediaID,
		arg.AdPositionID,
		arg.Price,
		arg.ChargeType,
		arg.DeviceID,
		arg.Ip,
		arg.Ua,
		arg.GeoCity,
		arg.FreqResult,
		arg.ClickID,
		arg.EventTime,
	)
	return err
}

const queryDashboardBreakdown = `-- name: QueryDashboardBreakdown :many
SELECT
  CASE WHEN $5::text = 'campaign' THEN c.id
       WHEN $5::text = 'adgroup' THEN ag.id
       WHEN $5::text = 'creative' THEN cr.id
  END AS id,
  CASE WHEN $5::text = 'campaign' THEN c.name
       WHEN $5::text = 'adgroup' THEN ag.name
       WHEN $5::text = 'creative' THEN cr.name
  END AS name,
  COALESCE(SUM(rh.impressions), 0)::bigint AS impressions,
  COALESCE(SUM(rh.clicks), 0)::bigint AS clicks,
  COALESCE(SUM(rh.cost), 0)::float8 AS cost
FROM report_hourly rh
LEFT JOIN campaign c ON c.id = rh.campaign_id
LEFT JOIN ad_group ag ON ag.id = rh.ad_group_id
LEFT JOIN creative cr ON cr.id = rh.creative_id
WHERE rh.advertiser_id = $1 AND rh.hour >= $2 AND rh.hour < $3
GROUP BY 1, 2
ORDER BY cost DESC
LIMIT $4
`

type QueryDashboardBreakdownParams struct {
	AdvertiserID int64     `json:"advertiser_id"`
	Hour         time.Time `json:"hour"`
	Hour_2       time.Time `json:"hour_2"`
	Limit        int32     `json:"limit"`
	Dimension    string    `json:"dimension"`
}

type QueryDashboardBreakdownRow struct {
	ID          interface{} `json:"id"`
	Name        interface{} `json:"name"`
	Impressions int64       `json:"impressions"`
	Clicks      int64       `json:"clicks"`
	Cost        float64     `json:"cost"`
}

func (q *Queries) QueryDashboardBreakdown(ctx context.Context, arg *QueryDashboardBreakdownParams) ([]*QueryDashboardBreakdownRow, error) {
	rows, err := q.db.Query(ctx, queryDashboardBreakdown,
		arg.AdvertiserID,
		arg.Hour,
		arg.Hour_2,
		arg.Limit,
		arg.Dimension,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*QueryDashboardBreakdownRow
	for rows.Next() {
		var i QueryDashboardBreakdownRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Impressions,
			&i.Clicks,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryEntityReport = `-- name: QueryEntityReport :many
SELECT hour, SUM(impressions)::bigint AS impressions, SUM(clicks)::bigint AS clicks, SUM(cost)::float8 AS cost
FROM report_hourly
WHERE advertiser_id = $1
  AND ($5::text = 'campaign' AND campaign_id = $2
    OR $5::text = 'adgroup' AND ad_group_id = $2
    OR $5::text = 'creative' AND creative_id = $2)
  AND hour >= $3 AND hour < $4
GROUP BY hour
ORDER BY hour ASC
`

type QueryEntityReportParams struct {
	AdvertiserID int64     `json:"advertiser_id"`
	CampaignID   int64     `json:"campaign_id"`
	Hour         time.Time `json:"hour"`
	Hour_2       time.Time `json:"hour_2"`
	Dimension    string    `json:"dimension"`
}

type QueryEntityReportRow struct {
	Hour        time.Time `json:"hour"`
	Impressions int64     `json:"impressions"`
	Clicks      int64     `json:"clicks"`
	Cost        float64   `json:"cost"`
}

func (q *Queries) QueryEntityReport(ctx context.Context, arg *QueryEntityReportParams) ([]*QueryEntityReportRow, error) {
	rows, err := q.db.Query(ctx, queryEntityReport,
		arg.AdvertiserID,
		arg.CampaignID,
		arg.Hour,
		arg.Hour_2,
		arg.Dimension,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*QueryEntityReportRow
	for rows.Next() {
		var i QueryEntityReportRow
		if err := rows.Scan(
			&i.Hour,
			&i.Impressions,
			&i.Clicks,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryEntitySubItems = `-- name: QueryEntitySubItems :many
SELECT
  CASE WHEN $5::text = 'campaign' THEN ag.id
       WHEN $5::text = 'adgroup' THEN cr.id
  END AS id,
  CASE WHEN $5::text = 'campaign' THEN ag.name
       WHEN $5::text = 'adgroup' THEN cr.name
  END AS name,
  COALESCE(SUM(rh.impressions), 0)::bigint AS impressions,
  COALESCE(SUM(rh.clicks), 0)::bigint AS clicks,
  COALESCE(SUM(rh.cost), 0)::float8 AS cost
FROM report_hourly rh
LEFT JOIN ad_group ag ON ag.id = rh.ad_group_id
LEFT JOIN creative cr ON cr.id = rh.creative_id
WHERE rh.advertiser_id = $1
  AND ($5::text = 'campaign' AND rh.campaign_id = $2
    OR $5::text = 'adgroup' AND rh.ad_group_id = $2)
  AND rh.hour >= $3 AND rh.hour < $4
GROUP BY 1, 2
ORDER BY cost DESC
LIMIT 10
`

type QueryEntitySubItemsParams struct {
	AdvertiserID int64     `json:"advertiser_id"`
	CampaignID   int64     `json:"campaign_id"`
	Hour         time.Time `json:"hour"`
	Hour_2       time.Time `json:"hour_2"`
	Dimension    string    `json:"dimension"`
}

type QueryEntitySubItemsRow struct {
	ID          interface{} `json:"id"`
	Name        interface{} `json:"name"`
	Impressions int64       `json:"impressions"`
	Clicks      int64       `json:"clicks"`
	Cost        float64     `json:"cost"`
}

func (q *Queries) QueryEntitySubItems(ctx context.Context, arg *QueryEntitySubItemsParams) ([]*QueryEntitySubItemsRow, error) {
	rows, err := q.db.Query(ctx, queryEntitySubItems,
		arg.AdvertiserID,
		arg.CampaignID,
		arg.Hour,
		arg.Hour_2,
		arg.Dimension,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*QueryEntitySubItemsRow
	for rows.Next() {
		var i QueryEntitySubItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Impressions,
			&i.Clicks,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryReport = `-- name: QueryReport :many
SELECT hour, advertiser_id, campaign_id, ad_group_id, creative_id, media_id, ad_position_id, impressions, clicks, conversions, cost, revenue, win_count, bid_count
FROM report_hourly WHERE advertiser_id = $1 AND hour >= $2 AND hour < $3
  AND ($4::bigint IS NULL OR campaign_id = $4::bigint)
  AND ($5::bigint IS NULL OR ad_group_id = $5::bigint)
ORDER BY hour DESC
`

type QueryReportParams struct {
	AdvertiserID int64     `json:"advertiser_id"`
	Hour         time.Time `json:"hour"`
	Hour_2       time.Time `json:"hour_2"`
	CampaignID   *int64    `json:"campaign_id"`
	AdGroupID    *int64    `json:"ad_group_id"`
}

type QueryReportRow struct {
	Hour         time.Time      `json:"hour"`
	AdvertiserID int64          `json:"advertiser_id"`
	CampaignID   int64          `json:"campaign_id"`
	AdGroupID    int64          `json:"ad_group_id"`
	CreativeID   int64          `json:"creative_id"`
	MediaID      int64          `json:"media_id"`
	AdPositionID int64          `json:"ad_position_id"`
	Impressions  *int64         `json:"impressions"`
	Clicks       *int64         `json:"clicks"`
	Conversions  *int64         `json:"conversions"`
	Cost         pgtype.Numeric `json:"cost"`
	Revenue      pgtype.Numeric `json:"revenue"`
	WinCount     *int64         `json:"win_count"`
	BidCount     *int64         `json:"bid_count"`
}

func (q *Queries) QueryReport(ctx context.Context, arg *QueryReportParams) ([]*QueryReportRow, error) {
	rows, err := q.db.Query(ctx, queryReport,
		arg.AdvertiserID,
		arg.Hour,
		arg.Hour_2,
		arg.CampaignID,
		arg.AdGroupID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*QueryReportRow
	for rows.Next() {
		var i QueryReportRow
		if err := rows.Scan(
			&i.Hour,
			&i.AdvertiserID,
			&i.CampaignID,
			&i.AdGroupID,
			&i.CreativeID,
			&i.MediaID,
			&i.AdPositionID,
			&i.Impressions,
			&i.Clicks,
			&i.Conversions,
			&i.Cost,
			&i.Revenue,
			&i.WinCount,
			&i.BidCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
