// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roi.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCostAndRevenue = `-- name: GetCostAndRevenue :one
SELECT
    COALESCE(SUM(cost_micros), 0)::bigint as cost_micros,
    COALESCE(SUM(revenue_micros), 0)::bigint as revenue_micros,
    COALESCE(SUM(conversions), 0)::bigint as conversions
FROM roi_metrics
WHERE advertiser_id = $1
    AND date >= $2
    AND date <= $3
    AND ($4::bigint IS NULL OR campaign_id = $4::bigint)
    AND ($5::bigint IS NULL OR adgroup_id = $5::bigint)
`

type GetCostAndRevenueParams struct {
	AdvertiserID int64       `json:"advertiser_id"`
	Date         pgtype.Date `json:"date"`
	Date_2       pgtype.Date `json:"date_2"`
	CampaignID   *int64      `json:"campaign_id"`
	AdgroupID    *int64      `json:"adgroup_id"`
}

type GetCostAndRevenueRow struct {
	CostMicros    int64 `json:"cost_micros"`
	RevenueMicros int64 `json:"revenue_micros"`
	Conversions   int64 `json:"conversions"`
}

func (q *Queries) GetCostAndRevenue(ctx context.Context, arg *GetCostAndRevenueParams) (*GetCostAndRevenueRow, error) {
	row := q.db.QueryRow(ctx, getCostAndRevenue,
		arg.AdvertiserID,
		arg.Date,
		arg.Date_2,
		arg.CampaignID,
		arg.AdgroupID,
	)
	var i GetCostAndRevenueRow
	err := row.Scan(&i.CostMicros, &i.RevenueMicros, &i.Conversions)
	return &i, err
}

const listROIMetricsByAdvertiser = `-- name: ListROIMetricsByAdvertiser :many
SELECT advertiser_id, COALESCE(campaign_id, 0)::bigint as campaign_id,
    SUM(cost_micros)::bigint as cost_micros, SUM(revenue_micros)::bigint as revenue_micros
FROM roi_metrics
WHERE date >= $1
GROUP BY advertiser_id, COALESCE(campaign_id, 0)
HAVING SUM(cost_micros) > 0
`

type ListROIMetricsByAdvertiserRow struct {
	AdvertiserID  int64 `json:"advertiser_id"`
	CampaignID    int64 `json:"campaign_id"`
	CostMicros    int64 `json:"cost_micros"`
	RevenueMicros int64 `json:"revenue_micros"`
}

func (q *Queries) ListROIMetricsByAdvertiser(ctx context.Context, date pgtype.Date) ([]*ListROIMetricsByAdvertiserRow, error) {
	rows, err := q.db.Query(ctx, listROIMetricsByAdvertiser, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListROIMetricsByAdvertiserRow
	for rows.Next() {
		var i ListROIMetricsByAdvertiserRow
		if err := rows.Scan(
			&i.AdvertiserID,
			&i.CampaignID,
			&i.CostMicros,
			&i.RevenueMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertROIMetrics = `-- name: UpsertROIMetrics :exec

INSERT INTO roi_metrics (advertiser_id, campaign_id, adgroup_id, date, cost_micros, revenue_micros, conversions, roas, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 0, now())
ON CONFLICT (advertiser_id, campaign_id, adgroup_id, date)
DO UPDATE SET
    cost_micros = roi_metrics.cost_micros + EXCLUDED.cost_micros,
    revenue_micros = roi_metrics.revenue_micros + EXCLUDED.revenue_micros,
    conversions = roi_metrics.conversions + EXCLUDED.conversions,
    roas = CASE
        WHEN roi_metrics.cost_micros + EXCLUDED.cost_micros > 0
        THEN (roi_metrics.revenue_micros + EXCLUDED.revenue_micros)::numeric / (roi_metrics.cost_micros + EXCLUDED.cost_micros)::numeric
        ELSE 0
    END,
    updated_at = now()
`

type UpsertROIMetricsParams struct {
	AdvertiserID  int64       `json:"advertiser_id"`
	CampaignID    *int64      `json:"campaign_id"`
	AdgroupID     *int64      `json:"adgroup_id"`
	Date          pgtype.Date `json:"date"`
	CostMicros    int64       `json:"cost_micros"`
	RevenueMicros int64       `json:"revenue_micros"`
	Conversions   int32       `json:"conversions"`
}

// ROI metrics queries
func (q *Queries) UpsertROIMetrics(ctx context.Context, arg *UpsertROIMetricsParams) error {
	_, err := q.db.Exec(ctx, upsertROIMetrics,
		arg.AdvertiserID,
		arg.CampaignID,
		arg.AdgroupID,
		arg.Date,
		arg.CostMicros,
		arg.RevenueMicros,
		arg.Conversions,
	)
	return err
}
