apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ad-manager
  labels:
    app: ad-manager
spec:
  replicas: {{ .Values.adManager.replicas }}
  selector:
    matchLabels:
      app: ad-manager
  template:
    metadata:
      labels:
        app: ad-manager
    spec:
      containers:
        - name: ad-manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/ad-manager"]
          ports:
            - containerPort: 8081
              name: http
            - containerPort: 9091
              name: grpc
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db
                  key: url
            - name: REDIS_URL
              value: {{ .Release.Name }}-redis-master:6379
            - name: S3_ENDPOINT
              value: http://{{ .Release.Name }}-seaweedfs-master:9000
            - name: ASSETS_PUBLIC_URL
              value: "https://assets.opendsp.io"
            - name: S3_BUCKET
              value: opendsp
          resources:
            {{- toYaml .Values.adManager.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ad-manager
spec:
  selector:
    app: ad-manager
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 9091
      targetPort: 9091
