apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-ad-server
spec:
  selector:
    matchLabels:
      app: ad-server
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-ad-manager
spec:
  selector:
    matchLabels:
      app: ad-manager
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
